version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: ['nodemon', '--exec', 'npm', 'test']

  # docker exec -it web npm run test -- --watchAll