sudo: required
service:
  - docker

before_install:
  - docker build -t atmosphericb/docker-production -f Dockerfile.dev .

script:
  - docker run -t atmosphericb/docker-production npm run test -- --coverage