sudo: required
service:
  - docker

before_install:
  - docker build -t atmosphericb/docker-production -f Dockerfile.dev .

script:
  - docker run -t atmosphericb/docker-production npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-994858606901"
  bycket_path: "dockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"